‚ùå Error: clang++ not found in toolchain!
/home/runner/toolchain/bin:
data
linux
macos
windows

/home/runner/toolchain/bin/data:
icon0.png
modules
param.sfo
pic0.png
right.sprx
template.gp4
template.xml

/home/runner/toolchain/bin/data/modules:
libSceFios2.prx
libc.prx

/home/runner/toolchain/bin/linux:
LIBORBIS-LICENSE.txt
PkgTool.Core
create-eboot
create-lib
readelf

/home/runner/toolchain/bin/macos:
LIBORBIS-LICENSE.txt
PkgTool.Core
create-eboot
create-lib
readelf

/home/runner/toolchain/bin/windows:
LIBORBIS-LICENSE.txt
LibOrbisPkg.dll
PkgEditor.exe
create-eboot.exe
create-lib.exe
readelf.exe
Error: Process completed with exit code 1.
