name: Build PS4 Payload

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Download OpenOrbis Toolchain
      run: |
        echo "Downloading Toolchain..."
        wget -q https://github.com/OpenOrbis/OpenOrbis-PS4-Toolchain/releases/download/v0.5.2/toolchain-linux.tar.gz
        tar -xzf toolchain-linux.tar.gz
        mv toolchain /home/runner/toolchain

    - name: Compile Payload
      run: |
        export OO_PS4_TOOLCHAIN=/home/runner/toolchain
        
        echo "Compiling..."
        $OO_PS4_TOOLCHAIN/bin/clang++ main.cpp -o psn_replacement.elf \
          -target x86_64-scei-ps4 \
          -I$OO_PS4_TOOLCHAIN/include \
          -L$OO_PS4_TOOLCHAIN/lib \
          -O2 -std=c++11 \
          -lSceNet -lSceUserService -lSceSystemService \
          -Wl,--gc-sections

    - name: Upload ELF Artifact
      uses: actions/upload-artifact@v4
      with:
        name: ps4-payload
        path: psn_replacement.elf
